import { ClientMenuItem } from "@/types/client/sidebar";
import {
  Activity,
  AlignJustify,
  AlertTriangle,
  ArrowDownWideNarrow,
  ArrowLeftRight,
  BadgeCheck,
  Building2,
  CalendarClock,
  Coins,
  Cpu,
  Database,
  GitBranch,
  GitFork,
  Globe,
  HardDrive,
  Hash,
  KeyRound,
  Layers,
  LayoutTemplate,
  Library,
  Link,
  Link2,
  List,
  ListOrdered,
  Lock,
  Monitor,
  Network,
  OctagonAlert,
  Package,
  Puzzle,
  RefreshCw,
  Route,
  ScanSearch,
  Search,
  Server,
  Shapes,
  Share2,
  Shield,
  Table2,
  TextSearch,
  Timer,
  TreeDeciduous,
  Triangle,
  Workflow,
} from "lucide-react";

export const csMenu: ClientMenuItem[] = [
  {
    type: "group",
    title: "자료구조",
    icon: GitBranch,
    children: [
      {
        label: "배열 & 연결 리스트",
        to: "/cs/ds/array-list",
        icon: List,
        subPathActive: true,
      },
      {
        label: "스택 & 큐",
        to: "/cs/ds/stack-queue",
        icon: ListOrdered,
        subPathActive: true,
      },
      {
        label: "해시 테이블",
        to: "/cs/ds/hash-table",
        icon: Hash,
        subPathActive: true,
      },
      {
        label: "트리",
        to: "/cs/ds/tree",
        icon: TreeDeciduous,
        subPathActive: true,
      },
      {
        label: "힙 & 우선순위 큐",
        to: "/cs/ds/heap",
        icon: Triangle,
        subPathActive: true,
      },
      {
        label: "그래프",
        to: "/cs/ds/graph",
        icon: Share2,
        subPathActive: true,
      },
      {
        label: "트라이",
        to: "/cs/ds/trie",
        icon: TextSearch,
        subPathActive: true,
      },
    ],
  },
  {
    type: "group",
    title: "알고리즘",
    icon: Cpu,
    children: [
      {
        label: "시간 & 공간 복잡도",
        to: "/cs/algo/big-o",
        icon: Timer,
        subPathActive: true,
      },
      {
        label: "정렬",
        to: "/cs/algo/sorting",
        icon: ArrowDownWideNarrow,
        subPathActive: true,
      },
      {
        label: "이진 탐색",
        to: "/cs/algo/binary-search",
        icon: Search,
        subPathActive: true,
      },
      {
        label: "해시 탐색",
        to: "/cs/algo/hash-search",
        icon: ScanSearch,
        subPathActive: true,
      },
      {
        label: "완전 탐색 & 백트래킹",
        to: "/cs/algo/brute-force",
        icon: Puzzle,
        subPathActive: true,
      },
      {
        label: "DFS & BFS",
        to: "/cs/algo/dfs-bfs",
        icon: GitFork,
        subPathActive: true,
      },
      {
        label: "동적 계획법",
        to: "/cs/algo/dp",
        icon: Table2,
        subPathActive: true,
      },
      {
        label: "그리디",
        to: "/cs/algo/greedy",
        icon: Coins,
        subPathActive: true,
      },
      {
        label: "최단 경로",
        to: "/cs/algo/shortest-path",
        icon: Route,
        subPathActive: true,
      },
    ],
  },
  {
    type: "group",
    title: "네트워크",
    icon: Network,
    children: [
      {
        label: "OSI 7계층 & TCP/IP",
        to: "/cs/network/osi",
        icon: Layers,
        subPathActive: true,
      },
      {
        label: "TCP & UDP",
        to: "/cs/network/tcp-udp",
        icon: ArrowLeftRight,
        subPathActive: true,
      },
      {
        label: "3-Way & 4-Way Handshake",
        to: "/cs/network/handshake",
        icon: RefreshCw,
        subPathActive: true,
      },
      {
        label: "IP 주소 & 서브네팅",
        to: "/cs/network/ip",
        icon: Globe,
        subPathActive: true,
      },
      {
        label: "HTTP & HTTPS",
        to: "/cs/network/http",
        icon: Link2,
        subPathActive: true,
      },
      {
        label: "DNS & 로드 밸런싱",
        to: "/cs/network/dns",
        icon: Server,
        subPathActive: true,
      },
      {
        label: "Cookie, Session & JWT",
        to: "/cs/network/auth",
        icon: KeyRound,
        subPathActive: true,
      },
    ],
  },
  {
    type: "group",
    title: "운영체제",
    icon: Monitor,
    children: [
      {
        label: "프로세스 & 스레드",
        to: "/cs/os/process-thread",
        icon: Workflow,
        subPathActive: true,
      },
      {
        label: "CPU 스케줄링",
        to: "/cs/os/cpu-scheduling",
        icon: CalendarClock,
        subPathActive: true,
      },
      {
        label: "컨텍스트 스위칭",
        to: "/cs/os/context-switching",
        icon: RefreshCw,
        subPathActive: true,
      },
      {
        label: "동기화 (Mutex, Semaphore)",
        to: "/cs/os/synchronization",
        icon: Lock,
        subPathActive: true,
      },
      {
        label: "교착 상태 (Deadlock)",
        to: "/cs/os/deadlock",
        icon: OctagonAlert,
        subPathActive: true,
      },
      {
        label: "가상 메모리 & 페이징",
        to: "/cs/os/virtual-memory",
        icon: HardDrive,
        subPathActive: true,
      },
      {
        label: "페이지 교체 알고리즘",
        to: "/cs/os/page-replacement",
        icon: RefreshCw,
        subPathActive: true,
      },
    ],
  },
  {
    type: "group",
    title: "데이터베이스",
    icon: Database,
    children: [
      {
        label: "RDBMS vs NoSQL",
        to: "/cs/db/rdbms-nosql",
        icon: Table2,
        subPathActive: true,
      },
      {
        label: "트랜잭션 & ACID",
        to: "/cs/db/transaction",
        icon: BadgeCheck,
        subPathActive: true,
      },
      {
        label: "데이터베이스 격리 수준",
        to: "/cs/db/isolation",
        icon: Shield,
        subPathActive: true,
      },
      {
        label: "인덱스 (B-Tree)",
        to: "/cs/db/index",
        icon: Library,
        subPathActive: true,
      },
      {
        label: "정규화 & 역정규화",
        to: "/cs/db/normalization",
        icon: AlignJustify,
        subPathActive: true,
      },
      {
        label: "조인 (Join)",
        to: "/cs/db/join",
        icon: Link,
        subPathActive: true,
      },
      {
        label: "이상 현상 (Anomaly)",
        to: "/cs/db/anomaly",
        icon: AlertTriangle,
        subPathActive: true,
      },
    ],
  },
  {
    type: "group",
    title: "디자인 패턴",
    icon: Layers,
    children: [
      {
        label: "SOLID 원칙",
        to: "/cs/pattern/solid",
        icon: Shapes,
        subPathActive: true,
      },
      {
        label: "생성 패턴",
        to: "/cs/pattern/creational",
        icon: Package,
        subPathActive: true,
      },
      {
        label: "구조 패턴",
        to: "/cs/pattern/structural",
        icon: Building2,
        subPathActive: true,
      },
      {
        label: "행위 패턴",
        to: "/cs/pattern/behavioral",
        icon: Activity,
        subPathActive: true,
      },
      {
        label: "MVC, MVP, MVVM",
        to: "/cs/pattern/mvc-mvp-mvvm",
        icon: LayoutTemplate,
        subPathActive: true,
      },
    ],
  },
];
